"""Phase C analysis, exactly as pre-registered in explore/EXPLORE.md (written before any confirmation run).

    python explore/confirm_stats.py        # prints the tables and writes explore/confirm_results.md
"""
from __future__ import annotations

import glob
import json
import math
import os

import numpy as np
from scipy import stats

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)


def runs(root, suite, arm, seeds):
    out = {}
    for s in seeds:
        p = f"{root}/{suite}_{arm}_s{s}/results.json"
        if os.path.exists(p):
            r = json.load(open(p))
            if r.get("metrics"):
                out[s] = r
    return out


def welch(a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    d = a.mean() - b.mean()
    va, vb = a.var(ddof=1) / len(a), b.var(ddof=1) / len(b)
    se = math.sqrt(va + vb)
    df = (va + vb) ** 2 / (va ** 2 / (len(a) - 1) + vb ** 2 / (len(b) - 1)) if se > 0 else 1.0
    t = d / se if se > 0 else 0.0
    p = 2 * stats.t.sf(abs(t), df)
    h = stats.t.ppf(0.975, df) * se
    return d, d - h, d + h, p


def holm(ps):
    order = np.argsort(ps)
    adj, m, run = [0.0] * len(ps), len(ps), 0.0
    for k, i in enumerate(order):
        run = max(run, min(1.0, (m - k) * ps[i]))
        adj[i] = run
    return adj


def never_learned(r):
    return sum(1 for i in range(len(r["R"])) if r["R"][i][i] < 0.5)


def summary(name, rs, T):
    acc = [r["metrics"]["ACC"] for r in rs.values()]
    fg = [r["metrics"]["FORGET"] for r in rs.values()]
    buf = rs and next(iter(rs.values())).get("method_kwargs", {}).get("buffer_per_task", 0)
    r0 = next(iter(rs.values())) if rs else None
    mem = r0["params"] * 4 / 1e6 + (buf or 0) * T * 188 / 1e6 if r0 else float("nan")
    rs_ = [r["replay_samples"] for r in rs.values()]
    cpu = [r["wall_time"] / 3600 for r in rs.values()]
    nl = sum(never_learned(r) for r in rs.values())
    return (f"| {name} | {len(acc)} | {np.mean(acc):.3f} ± {np.std(acc, ddof=1):.3f} | {np.mean(fg):.3f} | "
            f"{mem:.2f} | {np.mean(rs_) / 1e6:.3f}M | {np.mean(cpu):.3f} | {nl} |"), acc, fg


def family(title, root, suite, T, arms, tests, seeds):
    lines = [f"### {title}", "", "| arm | n | final ACC (mean ± SD) | FORGET | persistent MB | replayed | CPU h/run | "
             "never-learned tasks |", "|---|---|---|---|---|---|---|---|"]
    data = {}
    for label, arm in arms:
        rs = runs(root, suite, arm, seeds)
        line, acc, fg = summary(label, rs, T)
        lines.append(line)
        data[label] = dict(ACC=acc, FORGET=fg)
    res, ps = [], []
    for h, a, b, metric in tests:
        if len(data[a][metric]) < 2 or len(data[b][metric]) < 2:
            res.append((h, a, b, metric, None)); ps.append(1.0); continue
        d, lo, hi, p = welch(data[a][metric], data[b][metric])
        res.append((h, a, b, metric, (d, lo, hi, p))); ps.append(p)
    adj = holm(ps)
    lines += ["", "| test | comparison | metric | difference [95% CI] | Welch p | Holm p |", "|---|---|---|---|---|---|"]
    for (h, a, b, metric, v), pa in zip(res, adj):
        if v is None:
            lines.append(f"| {h} | {a} − {b} | {metric} | (missing) | | |")
        else:
            d, lo, hi, p = v
            lines.append(f"| {h} | {a} − {b} | {metric} | {d:+.3f} [{lo:+.3f}, {hi:+.3f}] | {p:.3g} | {pa:.3g} |")
    return lines


if __name__ == "__main__":
    out = ["# Phase C results (pre-registered; generated by explore/confirm_stats.py)", ""]
    out += family("C1: CNN fetch5, seeds 201-210", "explore/runs/confirm", "fetch5", 5,
                  [("LwF-int8", "lwf_int8"), ("replay@973", "replay_buf973"), ("isolation", "isolation")],
                  [("H1", "LwF-int8", "replay@973", "ACC"), ("H2", "LwF-int8", "replay@973", "FORGET"),
                   ("H3", "LwF-int8", "isolation", "ACC")], range(201, 211))
    out += [""]
    out += family("C2: SNN fetch3, seeds 201-208", "explore/runs/confirm_snn", "fetch3", 3,
                  [("LwF-int8", "lwf_int8"), ("replay@1380", "replay_buf1380")],
                  [("H4", "LwF-int8", "replay@1380", "ACC"), ("H5", "LwF-int8", "replay@1380", "FORGET")],
                  range(201, 209))
    text = "\n".join(out) + "\n"
    print(text)
    open("explore/confirm_results.md", "w").write(text)
