act_reg: 0.0
anneal_lr: true
ckpt_every: 20
clip_coef: 0.2
dfa: false
enc_kwargs: {}
encoder: cnn
ent_coef: 0.01
env_id: FetchObj-0
env_kwargs: {}
feat_dim: 128
gae_lambda: 0.95
gamma: 0.99
hidden: 64
lr: 0.001
max_grad_norm: 0.5
mem_cache: true
mem_kwargs: {}
memory: false
minibatch_size: 256
multihead: true
n_tasks: 3
num_envs: 16
num_steps: 128
out_dir: runs
run_name: fetch3_sleep_buf50_s2/task0
seed: 2
stdp: {}
target_kl: 0.03
task_id: 0
threads: 1
total_frames: 150000
update_epochs: 4
vf_coef: 0.5
window: 1
