act_reg: 0.0
anneal_lr: true
ckpt_every: 20
clip_coef: 0.2
dfa: false
dfa_scope: all
enc_kwargs:
  channels:
  - 8
  - 16
  - 32
encoder: cnn
ent_coef: 0.01
env_id: FetchObj5-4
env_kwargs: {}
feat_dim: 64
frame_stack: 1
gae_lambda: 0.95
gamma: 0.99
hidden: 64
lr: 0.001
max_grad_norm: 0.5
mem_cache: true
mem_kwargs: {}
memory: false
minibatch_size: 256
multihead: false
n_tasks: 1
num_envs: 16
num_steps: 128
out_dir: runs
run_name: fetch5_isolation_narrow_s203/task4
seed: 203
stdp: {}
target_kl: 0.03
task_id: 0
threads: 1
total_frames: 150000
update_epochs: 4
vf_coef: 0.5
window: 1
